# Generated by Django 4.1.5 on 2023-01-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('channel_image', models.ImageField(blank=True, upload_to='media')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='chat.server')),
            ],
        ),
    ]
